---
# Build and deploy Java Application
# -----------------------------------------------
- name: Create repository directory
  file: path=/opt/repos state=directory owner=tomcat group=tomcat mode=0755

- name: Clone repository
  git: repo=https://github.com/gyamin/stockTraceWeb.git
       dest=/opt/repos/stockTraceWeb
       version=develop

- name: Change repository owner
  file: path=/opt/repos/stockTraceWeb owner=tomcat group=tomcat state=directory recurse=yes

#- name: Debug
#  shell: bash -lc pwd chdir=/opt/repos/stockTraceWeb/app
#  register: debug
#
#- debug: var=debug

- name: Build application (Create war file)
  shell: source ~/.bash_profile;mvn package chdir=/opt/repos/stockTraceWeb/app
  become: True
  become_user: tomcat

# Notice: copyはローカルにあるファイルをリモートにコピーするコマンド
- name: Copy war file to tomcat webapps directory
  shell: creates=/usr/share/tomcat/webapps/stocktrace.war cp /opt/repos/stockTraceWeb/app/target/stocktrace.war /usr/share/tomcat/webapps/stocktrace.war
  become: True
  become_user: tomcat
  notify: restart tomcat

# Build javascript/css and deploy html files
# -----------------------------------------------
- name: Install nodejs
  yum: name=nodejs state=present

- name: Install TypeScript
  shell: npm install -g typescript

- name: Install npm modules
  shell: chdir=/opt/repos/stockTraceWeb/app/src/main/webapp/app npm install
  become: True
  become_user: tomcat

- name: Install bower modules
  shell: chdir=/opt/repos/stockTraceWeb/app/src/main/webapp/app/src ./../node_modules/bower/bin/bower install
  become: True
  become_user: tomcat

- name: Install typings modules
  shell: chdir=/opt/repos/stockTraceWeb/app/src/main/webapp/app/src ./../node_modules/typings/dist/bin.js install
  become: True
  become_user: tomcat

- name: Build javascript/css and deploy html
  shell: chdir=/opt/repos/stockTraceWeb/app/src/main/webapp/app npm run:clean;npm run build:all
  become: True
  become_user: tomcat

# JavaScript のcommonディレクトリは単体でbuildが必要
- name: Build javascript common
  shell: chdir=/opt/repos/stockTraceWeb/app/src/main/webapp/app/src/js/common tsc
  become: True
  become_user: tomcat

- name: Copy bower components
  shell: chdir=/opt/repos/stockTraceWeb/app/src/main/webapp/app npm run build:bower
  become: True
  become_user: tomcat

- name: Copy javascript/css and deploy html to tomcat webapps directory
  shell: chdir=/opt/repos/stockTraceWeb/app/src/main/webapp/app cp -Rf ./dist /opt/apache-tomcat-8.0.39/webapps/stocktrace/app/
  become: True
  become_user: tomcat