---
#- name: Add OS groups
#  group: name=admin gid=1000 state=present
#
#- name: Add OS users
#  user: name=gyamin comment="gyamin" uid=1001 group=admin

- name: Install EPEL Repository
  yum: name=epel-release state=present
  when: "ansible_os_family == 'RedHat' and ansible_distribution_major_version == '7'"

- name: Install wget
  yum: name=wget state=present