---
- name: Install nginx
  yum: name=nginx enablerepo=epel state=present

- name: Put nginx.conf
  template: src=nginx.conf dest=/etc/nginx mode=0644
  notify:
  - restart nginx

- name: Start nginx Server
  service: name=nginx enabled=yes state=started

- name: Install policycoreutils-python
  yum: name=policycoreutils-python state=present

- name: insert firewalld rule for tomcat http port
  firewalld: port=80/tcp permanent=true state=enabled immediate=yes
  when: "ansible_os_family == 'RedHat' and ansible_distribution_major_version == '7'"